name: Build CI

on: push

jobs:
    type_check:
        name: Type Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
            - name: Run Type Check
              run: pnpm tsc